### PR TITLE
Changed async poller to handle connection retries

### PR DESCRIPTION
**Pull request by dannylui**
New config option 'retry' added to play book tasks.

### CODE REVIEW

**Comment by ferrants** [comment]
So you would use this like:
```
- name: do something polling
  command: ./run_script.sh
  poll: 45
  async: 5
  retry: 5
```
Which would say that if 5 consecutive connections dropped then it should fail, right?

**Comment by dannylui** [comment]
Yup.  Well actually 6 consecutive connection drops actually.  The initial disconnect plus 5 retries is a total of 6 interruptions.

**Comment by cchristous** [comment]
Can we merge this?

**Comment by ferrants** [comment]
Sure, how/where should we begin using it?

**Comment by cchristous** [comment]
RTS integration testing, Command integration testing, RWH testing

**Comment by ferrants** [comment]
Do you have a modification to those jobs that installs ansible from somewhere? If we install ansible and designate the source as a parameter to the job, we'll have a good way of testing this change.

**Comment by cchristous** [comment]
@emuzykin can you update the warehouse job?

**Comment by cchristous** [comment]
or at least let me know what Jenkins job and dxansible files need to be updated

**Comment by emuzykin** [comment]
@cchristous - I was trying to figure out the context for your request. I think this is a modification for async. You can find the relevant code here for the RWH: https://github.com/dataxu/dxansible/blob/master/warehouse_wservice_test.yml

**Comment by cchristous** [comment]
I created https://github.com/dataxu/jenkins-jobs/pull/411 and https://github.com/dataxu/dxansible/pull/433. Please take a look

**Comment by ferrants** [comment]
I think if this functionality will ever make it to the ansible/ansible repo, this option would have to be set in the `ansible.cfg` file

**Pull request merged**
